import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    prevPrice: 2000,
    newPrice: 1000,
    company: "Nike",
    color: "white",
    category: "sneakers",
    discountPrice: 50,
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    prevPrice: 2000,
    newPrice: 1000,
    company: "Nike",
    color: "red",
    category: "sneakers",
    discountPrice: 50,
  },
  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    title: "Nike Waffle One Sneaker",
    prevPrice: 10000,
    newPrice: 5000,
    company: "Nike",
    color: "green",
    category: "sneakers",
    discountPrice: 50,
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Nike Running Shoe",
    prevPrice: 6000,
    newPrice: 5000,
    company: "Adidas",
    color: "black",
    category: "sneakers",
    discountPrice: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    prevPrice: 2000,
    newPrice: 1000,
    company: "Adidas",
    color: "black",
    category: "flats",
    discountPrice: 50,
  },
  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    prevPrice: 4000,
    newPrice: 1000,
    company: "Vans",
    color: "white",
    category: "flats",
    discountPrice: 75,
  },
  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    prevPrice: 6000,
    newPrice: 5000,
    company: "Nike",
    color: "green",
    category: "sneakers",
    discountPrice: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    prevPrice: 7000,
    newPrice: 5000,
    company: "Adidas",
    color: "blue",
    category: "sneakers",
    discountPrice: 29,
  },
  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    prevPrice: 6000,
    newPrice: 5000,
    company: "Puma",
    color: "yellow",
    category: "sneakers",
    discountPrice: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    prevPrice: 6000,
    newPrice: 5000,
    company: "Puma",
    color: "red",
    category: "sneakers",
    discountPrice: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    prevPrice: 7000,
    newPrice: 5000,
    company: "Puma",
    color: "black",
    category: "sneakers",
    discountPrice: 29,
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    prevPrice: 7000,
    newPrice: 5000,
    company: "Puma",
    color: "white",
    category: "sneakers",
    discountPrice: 29,
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    prevPrice: 16000,
    newPrice: 15000,
    company: "Puma",
    color: "black",
    category: "sneakers",
    discountPrice: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    prevPrice: 5000,
    newPrice: 1000,
    company: "Puma",
    color: "yellow",
    category: "sneakers",
    discountPrice: 80,
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    prevPrice: 600,
    newPrice: 500,
    company: "Vans",
    color: "red",
    category: "flats",
    discountPrice: 25,
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    prevPrice: 6000,
    newPrice: 5000,
    company: "Vans",
    color: "white",
    category: "sandals",
    discountPrice: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    prevPrice: 6000,
    newPrice: 5000,
    company: "Vans",
    color: "blue",
    category: "sandals",
    discountPrice: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    prevPrice: 17000,
    newPrice: 15000,
    company: "Nike",
    color: "black",
    category: "sandals",
    discountPrice: 80,
  },
];
export default data;
